### ISSUE TITLE
Attempted to call function "sprintf" from namespace "Safe".

### ISSUE THREAD

**Issue by Holicz** [Setono/SyliusCatalogPromotionPlugin#16]
This bundle is using Safe functions (e.g. in `Setono\SyliusCatalogPromotionPlugin\EventListener\AddTimestampableIndicesSubscriber`) but the Safe library is not listed as a requirement in `composer.json` so the developer has to require Safe themselves.

**Comment by loevgaard** [comment]
Hi @Holicz 

Thanks for finding this issue. I will provide fix in 10 minutes :)

**Comment by loevgaard** [comment]
Fixed in https://github.com/Setono/SyliusCatalogPromotionPlugin/pull/17 :)
