### ISSUE TITLE
How to implement other discount types?

### ISSUE THREAD

**Issue by RafalSumka** [Setono/SyliusCatalogPromotionPlugin#33]
Is there any way to customize this plugin and implement other discount types such as e.g fixed discount?

**Comment by loevgaard** [comment]
The fixed discount feature was removed to make it simpler at some point. I can't completely remember the reasoning behind it. Can you explain your use case and why the percentage wise thing won't do it? :)

**Comment by RafalSumka** [comment]
Well, the use case is pretty simple e.g temporary discount -$5 on every product for given taxon. I cannot do it with percentage discount.

**Comment by loevgaard** [comment]
Yeah, I see. Well, it's a big PR to add such a feature, and we would love to have it ourselves, but as of right now you'd have to figure out doing something else. It could be using this plugin for that instead: https://github.com/Setono/SyliusBulkEditPlugin

**Comment by RafalSumka** [comment]
OK, thanks. I'll probably fork the plugin and do necessary changes by myself :)

**Comment by loevgaard** [comment]
Great. Would appreciate a PR if you have the time :)

**Comment by loevgaard** [comment]
I think the reasoning for removing 'absolute discounts' was an example like this:

Promo 1: $5 discount
Promo 2: 10% discount

Given a product with price $15 there are two scenarios:

- Promo 1 is applied first: `($15 - $5) * 0.9 = $9`
- Promo 2 is applied first: `($15 * 0.9) - $5 = $8.5`

This would be difficult to debug for end users if they have many promos.
