### ISSUE TITLE
Unable to restore original price at end of promotion

### ISSUE THREAD

**Issue by jbcr** [Setono/SyliusCatalogPromotionPlugin#39]
Sylius version: 1.9
Setono Plugin version: 0.3.1

Step to reproduce:

1. Add a catalog promotion
2. Apply the promotion on products
3. Disable the promotion
4. Apply the promotion on products

Expected result:

In the end, all products must have the original price in price.

Actual result:

After disabling the promotion and applied the promotion, all products have the promotion price.

Suspected issue:

The updatePrices function does not update the price to restore the original price on older discounted products.
Why ? The bulkIdentifier is null and the updatePrices function update only the price with a specific bulkIdentifier

IMHO, the bulkIdentifier must be added on product updated on resetMultiplier function.

WDYT?

**Comment by loevgaard** [comment]
Hi @jbcr 

This is a serious bug if this is the case. Can you give me more details to actually be able to reproduce it? It seems you have 4 steps and after those 4 steps I would expect a promotion to be applied since that's your step 4.

**Comment by jbcr** [comment]
In step 2, the `setono:sylius-catalog-promotion:process` command apply the new discount for all products.

In step 4, the discount ends. The `setono:sylius-catalog-promotion:process` will remove the discount for all products and restore the original price.

But the resetMultiplier removes the discount on the multiplier without recalculating the new price. In version 0.2, the price for all products has been updated by the first query on `updatePrices` function.

In version 0.3, with the bulkIdentifier, all older discounted products are not updated...

Sorry, I have a lot of problems explaining the bug.

**Comment by jbcr** [comment]
Hi @loevgaard,

What is the way to resolve this issue? 

* add the BulkId on price when the multiplier is reset
* add a query to reset price into the multiplier reset method

**Comment by loevgaard** [comment]
Hi, @jbcr 

Can you check if the newest release of this plugin works better for you? :)
